// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class NodeData
	{
		public const uint NORTH_WALL = 1;
		public const uint EAST_WALL = 1 << 1;
		public const uint SOUTH_WALL = 1 << 2;
		public const uint WEST_WALL = 1 << 3;
		public int x;
		public int y;
		public uint walls = NORTH_WALL | EAST_WALL | SOUTH_WALL | WEST_WALL;
		public bool processed;
		public int speed;

		public NodeData (int x, int y)
		{
			this.x = x;
			this.y = y;
		}

		public bool HasWall (int direction)
		{
			if (direction==0)
				return (walls & NORTH_WALL) > 0;
			
			else if (direction==1)
				return (walls & EAST_WALL) > 0;
			
			else if (direction==2)
				return (walls & SOUTH_WALL) > 0;
			
			else if (direction==3)
				return (walls & WEST_WALL) > 0;
			
			return false;
		}
	}
}

